### PR TITLE
BigBlueButton v2.4

### LINKED ISSUE #133: Exposed port 8080 for nginx not configurable
Unfortunatelly the port 8080 is as far as I see manually defined within several configration files:

- ./mod/nginx/bigbluebutton:  listen 8080 default_server;
- ./mod/nginx/bigbluebutton:  listen [::]:8080 default_server;
- ./mod/https/site-ipv4only.conf:    proxy_pass http://127.0.0.1:8080;
- ./mod/https/site.conf:    proxy_pass http://$endpoint_addr:8080;
- ./mod/etherpad/etherpad-export.sh:curl -v -X POST "http://jodconverter:8080/lool/convert-to/$convertTo" \
- ./mod/bbb-web/office-convert.sh:curl -v -X POST "http://jodconverter:8080/lool/convert-to/$convertTo" \
- ./docs/existing-web-server.md:2. Now all the required Docker containers should be running. BigBlueButton listens to port 8080. Create a virtual host by which BigBlueButton will be publicly accessible (in this case, let's assume the following server name for the virtual host: `bbb.example.com`). Enable SSL for the new _https_ virtual host. Make sure that the SSL certificate you will be using is signed by a CA (Certificate Authority). You could generate an SSL certificate for free using Let's Encrypt. It is suggested to add some directives to the _http_ virtual host `bbb.example.com` to redirect all requests to the _https_ one.
- ./docs/existing-web-server.md:RewriteRule .* ws://127.0.0.1:8080%{REQUEST_URI} [P,QSA,L]
- ./docs/existing-web-server.md:	ProxyPass http://127.0.0.1:8080/
- ./docs/existing-web-server.md:	ProxyPassReverse http://127.0.0.1:8080/
- ./docker-compose.tmpl.yml:      BIGBLUEBUTTON_ENDPOINT: http://10.7.7.1:8080/bigbluebutton/api/
- ./docker-compose.tmpl.yml:      API_BASE_URL: http://10.7.7.1:8080/bigbluebutton/api/

This should be configurable as it will collide e.g. with a gitlab installation.

### PR DESCRIPTION
**Pull request by alangecker**
## ToDo's
- [x] Stable 2.4 Release (scheduled for December 2021) 
- [x] change default nginx port + breaking change notes #133 #109 
- [x] use `bbb-html5.yml` config overlay instead of full `settings.yml`
- [x] Working etherpad 1.8.16 https://github.com/mconf/ep_redis_publisher/issues/5

closes #133

### CODE REVIEW

**Comment by amuehle** [comment]
Stable 2.4 Release (scheduled for December 2021) -> isn't BigBlueButton 2.4-rc-7 released since 6 days?
We would like to use this Docker-Version with the official 2.4, if its official released (merged to main branch)

**Comment by alangecker** [comment]
@amuehle yes, BBB 2.4-rc-7 is released since a few days, but, as the name says, it is only a "Release Candidate" (rc), not considered as a stable release.

This branch already runs with `2.4-rc-7` which should work more or less already stable, but be aware, that is was not tested well yet, but I would be very happy if people do test it :D

if you still want to use it, try following:
```
git checkout v2.4.x
./scripts/upgrade
```

**Comment by amuehle** [comment]
@alangecker thank you for the support, already tried that with `git clone -b v2.4.x --recurse-submodules https://github.com/bigbluebutton/docker.git bbb-docker` (fresh install) and so far it it's working fine. Sorry somehow i missed the rc. We will make some more testing (We tested all features and so far all is working good, pentest with 10-20 Users is on the TODO list at the moment.) We will be happy to share the results (We also will test the server performance)

**Comment by amuehle** [comment]
One thing i forgot: The `jodconverter` container did not start with error:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Config data location '/etc/app/' does not exist

Action:

Check that the value '/etc/app/' is correct, or prefix it with 'optional:'
```
I think this problem comes from this: [https://github.com/EugenMayer/docker-image-jodconverter](https://github.com/EugenMayer/docker-image-jodconverter) repo. Seems like it got updated recently.
I started it with: `docker run --memory 512m  --rm -p 8080:8080 eugenmayer/jodconverter:rest
`
And the same error appeared. I got it fixed by modifying the `docker-compose.yml` file and adding:
```
    volumes:
      - ./application.properties:/etc/app/application.properties
```
to the `jodconverter:` section, and running `echo "server.port=8080" > application.properties`
I think this could be added to the Dockerfile? `mod/jodconverter/Dockerfile` but this is maybe the wrong repo for this report as it should be fixed in the `EugenMayer/docker-image-jodconverter` repo.

**Comment by lightweight** [comment]
Ah - I've just posted a fix for that jodconverter issue see #178 ...

**Comment by alangecker** [comment]
BBB 2.4 is finally release! :)

@lightweight your fix seems to work as well, thanks! :)

I'll merge this now. there will be a separate PR for the `develop` -> `main` release

**Pull request merged**
