### PR TITLE
WIP: BigBlueButton 2.5 + several other changes

### LINKED ISSUE #120: Allow bbb-docker to be used with a fork and a configurable branch or configurable tag
It would be nice, if bbb-docker could be used for local BBB development. As a first step into that direction it would be nice, if the hardcode official repo could be configured to target e.g. a fork and that the used tag or even a branch could be configured

### LINKED ISSUE #174: why is there no prebuilt image?
Hi,

I love that bbb is now available as a docker image!
And I was wondering why it is necessary to build all images locally? Couldn'nt there just ne some prebuilt image on docker hub just like for greenlight?

Regards
Dorian

### LINKED ISSUE #176: 2.4 how to use mediasoup
Hey,

can someone already say how to switch from kurento to mediasoup in the docker-variant?

thx

### LINKED ISSUE #189: use official coturn docker image
According to https://github.com/instrumentisto/coturn-docker-image the docker image is no longer maintained and https://hub.docker.com/r/coturn/coturn should be used instead. 

There also seem to be some configuration issues:
* Bad configuration format: dh2066
* You specified --lt-cred-mech and --use-auth-secret in the same time.
* Empty cli-password, and so telnet cli interface is disabled! Please set a non empty cli-password!
* socket: Protocol not supported
* configure PORT range to use. can be shared with kurento because both have host network and kernel should take care.

Many many thanks for the awesome BBB docker images! 
If nobody is working on it anyway, I can try to switch to the official coturn and create a pull reqeust. Will take a few weeks though.

### PR DESCRIPTION
**Pull request by alangecker**
- BigBlueButton 2.5
   * [x] mongodb 5.0
   * [x] ruby 2.7
   * [x] bbb-pads
   * [x] mediasoup support (closes #176)
- [x] Build images with officiall building container (https://gitlab.senfcall.de/senfcall-public/docker-bbb-build) for less maintenance work here and reduced inconsistencies
- [x] new `tags.env` containing all tags/versions, mainly for easier version picking after a new BBB release (closes #120)
- [x] updated images (closes #189)
- [x] publish images to registry (closes #174)
- [x] changelog entries
- [x] update docs (kurento references)
- [x] fix recordings
- [x] fix broken coturn container

### CODE REVIEW

**Comment by ffdixon** [comment]
Thanks again @alangecker for all your help!

**Comment by antobinary** [comment]
Nice! I have not tried MongoDB 5.0 yet, still on 4.4. I'd be curious to hear if you had to tweak anything. We'll likely be looking into MongoDB 5 for BBB 2.6 some time in the coming weeks

**Comment by alangecker** [comment]
@ffdixon you're welcome! :)

@antobinary ah really? I had some issues with meteor. After some research I read in the Meteor 2.6 changelog about MongoDB 5 and understood, wrongly, that it is also required - so I updated it.

The issue I had was, that the html5 client was throwing `MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017`, even though the correct IP (`10.7.7.6`) was provided via `MONGO_OPLOG_URL` and `MONGO_URL`.

I then found out, that the `127.0.0.1` IP comes from the replica set initialization:
```
mongo local --eval "rs.initiate({
   _id: 'rs0',
   members: [ { _id: 0, host: '127.0.0.1:27017' } ]
})"
```

So i had to change the IP there and tweak it a little bit, so it understands the IP as its own (would otherwise throw an error):
https://github.com/bigbluebutton/docker/pull/207/commits/dfbe11f74d7864c9f0c59586f4e726b7f9015601#diff-ea3370bd97067d0924ae828e100eda0e0700520e8ef23d380cbdda2baab12904

I switched to 5.0 and fixed this then, not sure anymore whether it was the same error before upgrading, but this shouldn't affect the normal bbb setup anyway since everything is accessible via localhost there.

It seems to work now flawlessly with 5.0, but haven't tested it extensively ;)

**Comment by alangecker** [comment]
BBB 2.5 is released and this here seems so far stable :)

I'll merge it now to `develop`, can be tested for some days and will then be merged to `main`

**Pull request merged**
